server:
  port: 8080

spring:
  application:
    name: gateway
  config:
    import: "optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  cloud:
    gateway:
      # 서비스 라우트는 각 서비스가 추출되는 단계에서 추가된다
      routes:
        - id: integration-service
          uri: lb://integration-service
          predicates:
            - Path=/juso/**,/gpt/**,/kakao-navi/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
